---
title: "BPCN in den Medien"
description: "Berichte über die Forschung der Abteilung BPCN in den Medien."
---

## Tell me who you are and I'll recognise your face better (2026)

Unsere Studie [It matters who you are: biography modulates the neural dynamics of facial identity representation](https://doi.org/10.1093/cercor/bhag010) (Shi, Gommlich und Kovács, *Cerebral Cortex*, 2026) zeigt, dass Wissen über eine Person die Repräsentation ihres Gesichts im Gehirn stärkt.

- [Meldung der Friedrich-Schiller-Universität Jena](https://www.uni-jena.de/en/398178/tell-me-who-you-are-and-i-ll-recognise-your-face-better) (auf Englisch), 1. April 2026

## Gesichter lernt das Gehirn am schnellsten im persönlichen Kontakt (2021)

Unsere Studie [Getting to know you: emerging neural representations during face familiarization](https://doi.org/10.1523/jneurosci.2466-20.2021) (Ambrus, Eick, Kaiser und Kovács, *Journal of Neuroscience*, 2021) zeigt, dass das mit Vertrautheit verbundene Hirnsignal am stärksten ist, wenn man eine Person persönlich kennengelernt hat. Die Pressemitteilung der Society for Neuroscience wurde vielfach aufgegriffen:

- [idw-Pressemitteilung](https://idw-online.de/de/news769613)
- [Deutsches Ärzteblatt](https://www.aerzteblatt.de/nachrichten/124548/Das-Gehirn-merkt-sich-Gesichter-nach-persoenlichem-Kontakt-besser)
- [Lichtgedanken, Magazin der Friedrich-Schiller-Universität Jena](https://www.lichtgedanken.uni-jena.de/en/1210/face-to-face) (auf Englisch)
- [EurekAlert!](https://www.eurekalert.org/pub_releases/2021-05/sfn-tbl051821.php) (auf Englisch)
- [Medical Xpress](https://medicalxpress.com/news/2021-05-brain-fastest-person.html) (auf Englisch)
- [CNN](https://edition.cnn.com/2021/06/07/health/face-to-face-brain-wellness-scn/index.html) (auf Englisch)
- [Nature](https://www.nature.com/articles/d41586-021-01415-y) (auf Englisch)
- [The Academic Times](https://academictimes.com/when-it-comes-to-finding-a-face-familiar-visual-cues-are-only-part-of-the-story/) (auf Englisch)
- [Inverse](https://www.inverse.com/mind-body/one-tip-to-make-friends) (auf Englisch)
- [Cognitive Neuroscience Society](https://www.cogneurosociety.org/getting-to-know-you-new-insights-in-facial-recognition/) (auf Englisch)
